default_language_version:
  python: python3.12
ci:
  skip:
  - ty
exclude: ^\.vscode/.*$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md,markdown']
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
    exclude: tests/data/.*
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
    exclude: '.devcontainer/.*'
  - id: pretty-format-json
    exclude: '.devcontainer/.*'
    args:
    - --indent
    - '4'
    - --autofix
    - --no-sort-keys
  - id: check-toml
  - id: fix-encoding-pragma
    args:
    - --remove
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.2
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: local
  hooks:
  - id: ty
    name: ty
    entry: uv run ty check --exit-zero-on-warning
    args:
    - cloudbot
    - plugins
    - tests
    language: system
    types: [python]
    pass_filenames: false
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 8d1b9cadaf854cb25bb0b0f5870e1cc66a083d6b  # frozen: 0.2.3
  hooks:
  - id: yamlfmt
    args:
    - --mapping
    - '2'
    - --sequence
    - '2'
    - --offset
    - '0'
    - --width
    - '120'
    - -e
    - -p
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.2
  hooks:
  - id: terraform_fmt
    files: ^infra/terraform/.*\.tf$
  - id: terraform_validate
    files: ^infra/terraform/.*\.tf$
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
    files: ^infra/terraform/.*\.sh$
