[pytest]
addopts =
    --doctest-modules
    --random-order
    --pythonhashseed=123
testpaths =
    tests
    cloudbot
filterwarnings =
    error
    ignore:pkg_resources is deprecated as an API:DeprecationWarning
    ignore:datetime.*:DeprecationWarning:sqlalchemy.*
    ignore:'cgi' is deprecated:DeprecationWarning
    ignore:`mcstatus.status_response` is deprecated:DeprecationWarning
asyncio_mode = auto
