[pytest]
addopts =
    --doctest-modules
    --random-order
    --pythonhashseed=123
testpaths =
    tests
    cloudbot
filterwarnings =
    error
    ignore:pkg_resources is deprecated as an API
    ignore:datetime.*:DeprecationWarning:sqlalchemy.*
    ignore:'cgi' is deprecated:DeprecationWarning
    ignore:`mcstatus.status_response` is deprecated:DeprecationWarning
    ignore:'audioop' is deprecated:DeprecationWarning:pydub.*
    ignore:Couldn't find ffmpeg or avconv:RuntimeWarning:pydub.*
    ignore:invalid escape sequence:DeprecationWarning
asyncio_mode = auto
