"""
hanb boards - predefined 61-cell hexagonal boards representing various
objects and structures at different scales.

Each board is a 61-character string using the hanb alphabet:
  abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.

Board naming convention: <category>_<name> -> <61-char string>

Categories:
  cosmic     - Stars, galaxies, nebulae, black holes
  planetary  - Planets, moons, asteroids, comets
  geographic - Continents, oceans, mountains, deserts
  city       - Cities, buildings, roads, parks
  nature     - Trees, animals, insects, flowers
  object     - Everyday objects, tools, food
  creature   - People, animals, mythical creatures
  structure  - Buildings, bridges, towers
  vehicle    - Cars, ships, aircraft
  weapon     - Swords, shields, bows
  magic      - Rings, potions, spells
  terrain    - Maps, dungeons, overworlds
  element    - Atoms, molecules, particles
  abstract   - Patterns, fractals, logic gates
"""

BOARDS = {
    # === COSMIC BOARDS ===
    "cosmic_milky_way": "----.3.3.--.-------.3.--.-.3.3.-.-.-.-.3.3.3.-.3.-.---.3.3.3.3.3.-.-.----.-.--.-.3.-.--.-.-.----.3.-.-.-.",
    "cosmic_andromeda": "a..3a.3a3a.a..a.3.aa.3a..a3.3a..aa..3.3..a.3a3.3a.3a..a..3a.3.3.aa.3a.a..a.3a..a.3a.aa..3a..a..a..3a.3a",
    "cosmic_black_hole": "aaaKaaaaKKaaKKaKKaaaaKaaaaaaaKaaaJaaaaaaaaaaaJaaaaJaaJaaaaaa",
    "cosmic_nebula": "a..C.3.C3C.a..a.3.CC.3C..aC.3C..aa..3.3..a.3C3.3C.3C..a..3C.3.3.CC.3C.a..a.3C..a.3C.CC..3C..a..a..3C.3C",
    "cosmic_pulsar": "aaaaaaaTaaaaTaaaaTaaTaaaaTaaaTaaaaTaaTaaaaTaTaaaaTTaaaaaaa",
    "cosmic_quasar": "aaaaaaaXaaaaXaaaXaXaaaXaXaaaaXaaaXaaaXaXaaaaXaXaaaXaXaaaXaXaXaaaaX",
    "cosmic_supernova": "a..SSS.SSS.a..a.SSSS.SSS..aS.SS..aa..S.S..a.SSS.SS.SS..a..SS.S.S.SS.SS.a..a.SS..a.SS.SS..SS..a..a..SS.SS",
    "cosmic_dark_matter": "a.....a.....a...a....a....a.a..a....a...a.....a..a..a..a....a...a....a.a....a....a.....a.....a",
    "cosmic_gamma_burst": "aaaaaaXaaaaaXaaaaXaaXaaaaaXaaaXaaaaXaaXaaaaXaXaaaaXXaaaaaaa",
    "cosmic_star_cluster": "a..9.9.99.a..a.9.99.99..a9.99..aa..9.9..a.999.99.99..a..99.9.9.99.99.a..a.99..a.99.99..99..a..a..99.99",
    "cosmic_solar_system": "AAAAAAAARAAAAAAAAAARAAQAARAAAAAAAAAXAAAAAAAAAAAAAAARAAAAAAAAAAAAAAQA",
    "cosmic_binary_star": "aaaaaaaTaaaaTaaTaaTaaaaTaaTaaaaTaaTaaTaaaaTaaTaaTaaTaaTaaaaaaa",
    "cosmic_globular_cluster": "a..5.5.55.a..a.5.55.55..a5.55..aa..5.5..a.555.55.55..a..55.5.5.55.55.a..a.55..a.55.55..55..a..a..55.55",
    "cosmic_void": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "cosmic_cosmic_web": "a.-.3.-.3.a..a.3.-.3.a..a.-.3.-.3.a.a..-.-.a.3.3.3.-.3.a..a.3.-.3.a.3.3.a.3.a.-.3.a.a..3.a..-.-.3.a",

    # === PLANETARY BOARDS ===
    "planetary_earth": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "planetary_mars": "a..K.K.K..a..a.K..K..aa.KK.KK..aa.KK..KK..aa.KK..KK..aa.KK..KK..aa.KK.KK..aa.K.K..K..a..a.K.K.K..a..a",
    "planetary_jupiter": "a..L.L.L..a..a.L..L..aa.LL.LL..aa.LL..LL..aa.LL..LL..aa.LL..LL..aa.LL.LL..aa.L.L..L..a..a.L.L.L..a..a",
    "planetary_saturn": "a..L.L.L..a..a.L..L..aa.LL.LL..aa.LL..LL..aa.LL..LL..aa.LL..LL..aa.LL.LL..aa.L.L..L..a..a.L.L.L..a..a",
    "planetary_venus": "a..J.J.J..a..a.J..J..aa.JJ.JJ..aa.JJ..JJ..aa.JJ..JJ..aa.JJ..JJ..aa.JJ.JJ..aa.J.J..J..a..a.J.J.J..a..a",
    "planetary_mercury": "a..I.I.I..a..a.I..I..aa.II.II..aa.II..II..aa.II..II..aa.II..II..aa.II.II..aa.I.I..I..a..a.I.I.I..a..a",
    "planetary_moon": "a..I.I.I..a..a.I..I..aa.II.II..aa.II..II..aa.II..II..aa.II..II..aa.II.II..aa.I.I..I..a..a.I.I.I..a..a",
    "planetary_asteroid_belt": "a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a",
    "planetary_comet": "aaaaaaaCaaaaCaaCaaaaCaaaCaaaaCaaCaaaaCaCaaaaCCaaaaaaa",
    "planetary_dwarf_planet": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "planetary_gas_giant": "a..M.M.M..a..a.M..M..aa.MM.MM..aa.MM..MM..aa.MM..MM..aa.MM..MM..aa.MM.MM..aa.M.M..M..a..a.M.M.M..a..a",
    "planetary_ice_giant": "a..L.L.L..a..a.L..L..aa.LL.LL..aa.LL..LL..aa.LL..LL..aa.LL..LL..aa.LL.LL..aa.L.L..L..a..a.L.L.L..a..a",
    "planetary_exoplanet_hot_jupiter": "a..M.M.M..a..a.M..M..aa.MM.MM..aa.MM..MM..aa.MM..MM..aa.MM..MM..aa.MM.MM..aa.M.M..M..a..a.M.M.M..a..a",
    "planetary_exoplanet_rocky": "a..K.K.K..a..a.K..K..aa.KK.KK..aa.KK..KK..aa.KK..KK..aa.KK..KK..aa.KK.KK..aa.K.K..K..a..a.K.K.K..a..a",
    "planetary_titan": "a..J.J.J..a..a.J..J..aa.JJ.JJ..aa.JJ..JJ..aa.JJ..JJ..aa.JJ..JJ..aa.JJ.JJ..aa.J.J..J..a..a.J.J.J..a..a",
    "planetary_europa": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "planetary_ganymede": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "planetary_triton": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "planetary_pluto": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "planetary_ceres": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "planetary_eris": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",

    # === GEOGRAPHIC BOARDS ===
    "geographic_pangaea": "AAAAAAPAAPAAAAPAAAAAAAAAAAAAAPAAAAAAAAPAAPAAAAAAAAAAAAAAAAAA",
    "geographic_ocean": "a.......a.....a....a....a.a..a....a...a.....a..a..a..a....a...a....a.a....a....a.....a.....a",
    "geographic_mountain_range": "aaaaPaaPPaaPaaPPaaPPaaPaaaaaaPaaPPaaPaaPPaaPPaaPaaaaaa",
    "geographic_volcano": "aaaaaaaPaaaaPaaPaaaaPaaaPaaaaPaaPaaaaPaPaaaaPPaaaaaaa",
    "geographic_island": "aaaaaaaOaaaaOaaOaaaaOaaaOaaaaOaaOaaaaOaOaaaaOOaaaaaaa",
    "geographic_desert": "a..S.S.S..a..a.S..S..aa.SS.SS..aa.SS..SS..aa.SS..SS..aa.SS..SS..aa.SS.SS..aa.S.S..S..a..a.S.S.S..a..a",
    "geographic_river": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "geographic_glacier": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "geographic_forest": "a..L.L.L..a..a.L..L..aa.LL.LL..aa.LL..LL..aa.LL..LL..aa.LL..LL..aa.LL.LL..aa.L.L..L..a..a.L.L.L..a..a",
    "geographic_tundra": "a..N.N.N..a..a.N..N..aa.NN.NN..aa.NN..NN..aa.NN..NN..aa.NN..NN..aa.NN.NN..aa.N.N..N..a..a.N.N.N..a..a",
    "geographic_jungle": "a..L.L.L..a..a.L..L..aa.LL.LL..aa.LL..LL..aa.LL..LL..aa.LL..LL..aa.LL.LL..aa.L.L..L..a..a.L.L.L..a..a",
    "geographic_savanna": "a..M.M.M..a..a.M..M..aa.MM.MM..aa.MM..MM..aa.MM..MM..aa.MM..MM..aa.MM.MM..aa.M.M..M..a..a.M.M.M..a..a",
    "geographic_swamp": "a..M.M.M..a..a.M..M..aa.MM.MM..aa.MM..MM..aa.MM..MM..aa.MM..MM..aa.MM.MM..aa.M.M..M..a..a.M.M.M..a..a",
    "geographic_canyon": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "geographic_reef": "a..I.I.I..a..a.I..I..aa.II.II..aa.II..II..aa.II..II..aa.II..II..aa.II.II..aa.I.I..I..a..a.I.I.I..a..a",
    "geographic_continent_north": "AAAAAAAPAAAAPAAPAAAAAAAAAAAAAAPAAAAAAAAPAAPAAAAAAAAAAAAAAAAAA",

    # === CITY BOARDS ===
    "city_tourist_map": "aaaaAAAANaaaAANaaaaKMaKAaaaaaNaaKaaaLLaAAAAAMAAMAAAALLAAAAAA",
    "city_downtown": "aaaaaaaAAAAAANAAAAAAMAAAAAAAAAAAALLAAAAAAAAMAAAALLAAAAAA",
    "city_residential": "aaaaaaaMaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "city_industrial": "aaaaaaaNaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "city_port": "aaaaaaaOaaaOaaOaaaaOaaaOaaaaOaaOaaaaOaOaaaaOOaaaaaaa",
    "city_airport": "aaaaaaaPaaaPaaPaaaaPaaaPaaaaPaaPaaaaPaPaaaaPPaaaaaaa",
    "city_park": "aaaaaaaLaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "city_highway": "aaaaNaaaaNaaaaNaaaaNaaaaNaaaaNaaaaNaaaaNaaaaNaaaaN",
    "city_metro": "aaaaNaaaNaaNaaaaNaaaNaaNaaaaNaaaNaaNaaaaNaaaNaaNaaaaN",
    "city_shopping_district": "aaaaaaaJaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "city_cathedral": "aaaaaaaMaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "city_stadium": "aaaaaaaNaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "city_university": "aaaaaaaMaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "city_hospital": "aaaaaaaMaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "city_marketplace": "aaaaaaaJaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",

    # === NATURE BOARDS ===
    "nature_oak_tree": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "nature_pine_tree": "aaaaaaaLaaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "nature_flower": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "nature_mushroom": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "nature_spider_web": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "nature_honeycomb": "a..H.H.H..a..a.H..H..aa.HH.HH..aa.HH..HH..aa.HH..HH..aa.HH..HH..aa.HH.HH..aa.H.H..H..a..a.H.H.H..a..a",
    "nature_coral_reef": "a..I.I.I..a..a.I..I..aa.II.II..aa.II..II..aa.II..II..aa.II..II..aa.II.II..aa.I.I..I..a..a.I.I.I..a..a",
    "nature_cave": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "nature_waterfall": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "nature_snowflake": "aaaaaaaHaaaaHaaHaaaaHaaaHaaaaHaaHaaaaHaHaaaaHHaaaaaaa",
    "nature_lightning": "aaaaaSaaaSaaaSSaaaSSaaaaSSSaaaSSSSSaaaaSSSSSSaaaaSSS",
    "nature_rainbow": "aaaaaaRQPOOOOOOPQQQRROOOOPQQRROOOOPQQQRROOOOPQQQR",
    "nature_tornado": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "nature_tsunami": "aaaaOaaOOaaOaaOOaaOOaaOaaaaaaOaaOOaaOaaOOaaOOaaOaaaaaa",
    "nature_aurora": "a..O.O.O..a..a.O..O..aa.OO.OO..aa.OO..OO..aa.OO..OO..aa.OO..OO..aa.OO.OO..aa.O.O..O..a..a.O.O.O..a..a",

    # === OBJECT BOARDS ===
    "object_apple": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_sword": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_shield": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_key": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "object_crown": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_chest": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_coin": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "object_potion": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "object_book": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_ring": "aaHaaaaGGaaaaFFFaaaaFaaFaaaaFaaaFaaaaFaaFaaaaFaFaaaaFFaaaaaaa",
    "object_gem": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "object_cup": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "object_bow": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "object_arrow": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_map": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_torch": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "object_door": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "object_window": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "object_bridge": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "object_ladder": "aaaaHaaHHaaHaaHHaaHHaaHaaaaaaHaaHHaaHaaHHaaHHaaHaaaaaa",

    # === CREATURE BOARDS ===
    "creature_person": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "creature_wolf": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "creature_dragon": "aaaaPaaPPaaPaaPPaaPPaaPaaaaaaPaaPPaaPaaPPaaPPaaPaaaaaa",
    "creature_phoenix": "aaaaaaaLaaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "creature_griffin": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "creature_unicorn": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "creature_troll": "aaaaaaaLaaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "creature_goblin": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "creature_giant_spider": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "creature_skeleton": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "creature_ghost": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "creature_vampire": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "creature_demon": "aaaaMaaMMaaMaaMMaaMMaaMaaaaaaMaaMMaaMaaMMaaMMaaMaaaaaa",
    "creature_angel": "aaaaLaaLLaaLaaLLaaLLaaLaaaaaaLaaLLaaLaaLLaaLLaaLaaaaaa",
    "creature_cat": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "creature_dog": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "creature_horse": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "creature_eagle": "aaaaaaaLaaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "creature_fish": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "creature_snake": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",

    # === STRUCTURE BOARDS ===
    "structure_castle": "aaaaPaaPPaaPaaPPaaPPaaPaaaaaaPaaPPaaPaaPPaaPPaaPaaaaaa",
    "structure_tower": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "structure_village": "aaaaaaaMaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "structure_fortress": "aaaaPaaPPaaPaaPPaaPPaaPaaaaaaPaaPPaaPaaPPaaPPaaPaaaaaa",
    "structure_temple": "aaaaMaaMMaaMaaMMaaMMaaMaaaaaaMaaMMaaMaaMMaaMMaaMaaaaaa",
    "structure_mine": "aaaaHaaHHaaHaaHHaaHHaaHaaaaaaHaaHHaaHaaHHaaHHaaHaaaaaa",
    "structure_dock": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "structure_wall": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "structure_gate": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "structure_farm": "aaaaaaaLaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "structure_mill": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "structure_inn": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "structure_lighthouse": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "structure_aqueduct": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "structure_pyramid": "aaaaPaaPPaaPaaPPaaPPaaPaaaaaaPaaPPaaPaaPPaaPPaaPaaaaaa",

    # === VEHICLE BOARDS ===
    "vehicle_car": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "vehicle_ship": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "vehicle_airplane": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "vehicle_horse_cart": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "vehicle_carriage": "aaaaaaaLaaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "vehicle_canoe": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "vehicle_galley": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "vehicle_chariot": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "vehicle_bicycle": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "vehicle_submarine": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "vehicle_rocket": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "vehicle_hot_air_balloon": "aaaaaaaOaaaaOaaOaaaaOaaaOaaaaOaaOaaaaOaOaaaaOOaaaaaaa",
    "vehicle_train": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "vehicle_tank": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "vehicle_helicopter": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",

    # === WEAPON BOARDS ===
    "weapon_sword": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "weapon_axe": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "weapon_spear": "aaaaaaaLaaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "weapon_bow": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "weapon_crossbow": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "weapon_staff": "aaaaaaaLaaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "weapon_dagger": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "weapon_hammer": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "weapon_mace": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "weapon_trident": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "weapon_shield": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "weapon_catapult": "aaaaMaaMMaaMaaMMaaMMaaMaaaaaaMaaMMaaMaaMMaaMMaaMaaaaaa",
    "weapon_cannon": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "weapon_katana": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",
    "weapon_war_hammer": "aaaaaaaKaaaaKaaKaaaaKaaaKaaaaKaaKaaaaKaKaaaaKKaaaaaaa",

    # === MAGIC BOARDS ===
    "magic_ring": "aaHaaaaGGaaaaFFFaaaaFaaFaaaaFaaaFaaaaFaaFaaaaFaFaaaaFFaaaaaaa",
    "magic_potion_health": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "magic_potion_mana": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "magic_spell_fire": "aaaaLaaLLaaLaaLLaaLLaaLaaaaaaLaaLLaaLaaLLaaLLaaLaaaaaa",
    "magic_spell_ice": "aaaaIaaIIaaIaaIIaaIIaaIaaaaaaIaaIIaaIaaIIaaIIaaIaaaaaa",
    "magic_spell_lightning": "aaaaLaaLLaaLaaLLaaLLaaLaaaaaaLaaLLaaLaaLLaaLLaaLaaaaaa",
    "magic_spell_heal": "aaaaIaaIIaaIaaIIaaIIaaIaaaaaaIaaIIaaIaaIIaaIIaaIaaaaaa",
    "magic_enchantment": "aaHaaaaGGaaaaFFFaaaaFaaFaaaaFaaaFaaaaFaaFaaaaFaFaaaaFFaaaaaaa",
    "magic_portal": "aaaaPaaPPaaPaaPPaaPPaaPaaaaaaPaaPPaaPaaPPaaPPaaPaaaaaa",
    "magic_scroll": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "magic_wand": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "magic_crystal_ball": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "magic_rune": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "magic_totem": "aaaaaaaMaaaaMaaMaaaaMaaaMaaaaMaaMaaaaMaMaaaaMMaaaaaaa",
    "magic_amulet": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",

    # === TERRAIN BOARDS ===
    "terrain_walking_map": "aaaaaKaaaaaKKaaKKaaaaaKaaaaaaaKaaaJaaaaaaaaaaaJaaaaJaaJaaaaaa",
    "terrain_hamlet_overmap": "aaaaaaaaKaaaKaaaLaaaaLaaaaaaaaaaaLaaaLaaaaaaaaaaLaaKaKaaaaaaa",
    "terrain_village_quest": "aaaaaaaaaaaaaMaMaaaaaaaaaaaaaMaaaaaaaaaaMaaaLaaaLaaaMaaaaaaa",
    "terrain_city_map": "aaaaaAAAANaaaaaNaaaaKMaKAaaaaaNaaKaaaLLaAAAAAMAAMAAAALLAAAAAA",
    "terrain_kingdom": "aaaaaaAAMOKaaKaAAaaONNaaOaaAANOMaAaaaaaKaaaaaMAAMaaLAAOaaaaaa",
    "terrain_continent": "AAAAAAAAAAPAAAAPAAAAAAAAAAAAAAPAAAAAAAAPAAPAAAAAAAAAAAAAAAAAA",
    "terrain_planet_map": "AAAAAAAAQAAAQAQQAAAQAAAQAAAAAAAAAAAAAQQQAAAAAAQAAAAAAAAAAAAA",
    "terrain_dungeon_entrance": "aaaaHaaHHaaHaaHHaaHHaaHaaaaaaHaaHHaaHaaHHaaHHaaHaaaaaa",
    "terrain_dungeon_floor1": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "terrain_dungeon_boss": "aaaaPaaPPaaPaaPPaaPPaaPaaaaaaPaaPPaaPaaPPaaPPaaPaaaaaa",
    "terrain_treasure_room": "aaaaJaaJJaaJaaJJaaJJaaJaaaaaaJaaJJaaJaaJJaaJJaaJaaaaaa",
    "terrain_trap_room": "aaaaHaaHHaaHaaHHaaHHaaHaaaaaaHaaHHaaHaaHHaaHHaaHaaaaaa",
    "terrain_forest_path": "aaaaaLaaaaaLLaaLLaaaaaLaaaaaaaLaaaKaaaaaaaaaaaKaaaaKaaKaaaaaa",
    "terrain_desert_oasis": "aaaaaSaaaaaSSaaSSaaaaaSaaaaaaaSaaaOaaaaaaaaaaaOaaaaOaaOaaaaaa",
    "terrain_mountain_pass": "aaaaaPaaaaaPPaaPPaaaaaPaaaaaaaPaaaNaaaaaaaaaaaNaaaaNaaNaaaaaa",
    "terrain_swamp_path": "aaaaaMaaaaaMMaaMMaaaaaMaaaaaaaMaaaLaaaaaaaaaaaLaaaaLaaLaaaaaa",

    # === ELEMENT BOARDS ===
    "element_lithium_atom": "a..-.--.-.-.-.a..-.--.-.-.-.--.a..-.--.-.-.-.--.--.-.-.a..-.--.-.-.--.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.v.-.-.a..a",
    "element_hydrogen": "a..-.--.-.-.-.a..-.--.-.-.-.--.a..-.--.-.-.-.--.--.-.-.a..-.--.-.-.--.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.v.-.-.a..a",
    "element_carbon": "a..-.--.-.-.-.a..-.--.-.-.-.--.a..-.--.-.-.-.--.--.-.-.a..-.--.-.-.--.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.v.-.-.a..a",
    "element_oxygen": "a..-.--.-.-.-.a..-.--.-.-.-.--.a..-.--.-.-.-.--.--.-.-.a..-.--.-.-.--.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.v.-.-.a..a",
    "element_iron": "a..-.--.-.-.-.a..-.--.-.-.-.--.a..-.--.-.-.-.--.--.-.-.a..-.--.-.-.--.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.v.-.-.a..a",
    "element_gold": "a..-.--.-.-.-.a..-.--.-.-.-.--.a..-.--.-.-.-.--.--.-.-.a..-.--.-.-.--.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.--.-.-.--.-.-.-.a..-.v.-.-.a..a",
    "element_water_molecule": "aaaaaaaHaaaaHaaHaaaaHaaaHaaaaHaaHaaaaHaHaaaaHHaaaaaaa",
    "element_co2_molecule": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "element_dna_helix": "aaaaMaaMMaaMaaMMaaMMaaMaaaaaaMaaMMaaMaaMMaaMMaaMaaaaaa",
    "element_proton": "aaaaaaaBaaaaBaaBaaaaBaaaBaaaaBaaBaaaaBaBaaaaBBaaaaaaa",
    "element_neutron": "aaaaaaaBaaaaBaaBaaaaBaaaBaaaaBaaBaaaaBaBaaaaBBaaaaaaa",
    "element_electron": "aaaaaaAaaaaAaAaaaaAaAaaaaAaAaAaAaAaAaAaAaaaaAaAaAaa",
    "element_quark_up": "aaaaaaaCaaaaCaaCaaaaCaaaCaaaaCaaCaaaaCaCaaaaCCaaaaaaa",
    "element_quark_down": "aaaaaaaCaaaaCaaCaaaaCaaaCaaaaCaaCaaaaCaCaaaaCCaaaaaaa",
    "element_gluon": "aaaaaaaBaaaaBaaBaaaaBaaaBaaaaBaaBaaaaBaBaaaaBBaaaaaaa",

    # === ABSTRACT BOARDS ===
    "abstract_null_gate": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "abstract_and_gate": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "abstract_or_gate": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "abstract_xor_gate": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "abstract_nand_gate": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "abstract_identity": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "abstract_checkerboard": "a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a",
    "abstract_spiral": "aaaaHaaHGaaHaaHGaaGHaaHaaaaaaHaaHGaaHaaHGaaGHaaHaaaaaa",
    "abstract_diamond": "aaaaaaaLaaaaLaaLaaaaLaaaLaaaaLaaLaaaaLaLaaaaLLaaaaaaa",
    "abstract_cross": "aaaaNaaNNaaNaaNNaaNNaaNaaaaaaNaaNNaaNaaNNaaNNaaNaaaaaa",
    "abstract_triangle": "aaaaaaaNaaaaNaaNaaaaNaaaNaaaaNaaNaaaaNaNaaaaNNaaaaaaa",
    "abstract_wave": "aHaaHHaaHaaHHaaHHaaHaaHHaaHaaHHaaHHaaHaaHHaaHaaHHaaHHaaHaaHH",
    "abstract_fractal": "a..H.H.H..a..a.H..H..aa.HH.HH..aa.HH..HH..aa.HH..HH..aa.HH..HH..aa.HH.HH..aa.H.H..H..a..a.H.H.H..a..a",
    "abstract_sierpinski": "aaaaaaaHaaaaHaaHaaaaHaaaHaaaaHaaHaaaaHaHaaaaHHaaaaaaa",
    "abstract_penrose": "a..a.a.a..a..a.a..a..aa..aa..aa..a.a.a..aa..a.a..a..aa..aa..aa..a.a..a.a..a..aa..aa..a.a.a..aa..a.a.a..aa..a..a",
    "abstract_mandelbrot": "a..N.N.N..a..a.N..N..aa.NN.NN..aa.NN..NN..aa.NN..NN..aa.NN..NN..aa.NN.NN..aa.N.N..N..a..a.N.N.N..a..a",

    # === FOOD BOARDS ===
    "food_bread": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "food_apple_pie": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "food_wine": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "food_cheese": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "food_fish_dish": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "food_honey": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "food_mushroom_soup": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
    "food_roast": "aaaaaaaJaaaaJaaJaaaaJaaaJaaaaJaaJaaaaJaJaaaaJJaaaaaaa",
    "food_herbs": "aaaaaaaHaaaaHaaHaaaaHaaaHaaaaHaaHaaaaHaHaaaaHHaaaaaaa",
    "food_spices": "aaaaaaaIaaaaIaaIaaaaIaaaIaaaaIaaIaaaaIaIaaaaIIaaaaaaa",
}
