name: Pylint analysis
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install apt deps
      run: sudo apt-get update && sudo apt-get install -qq -y libxml2-dev libxslt1-dev
    - name: Install dependencies
      run: uv sync --all-groups
    - name: Run pylint
      run: uv run pre-commit run pylint --all-files
